### ISSUE TITLE
Initial Screen

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#2]
Develop the welcome screen with all its required modules.
(This screen asks the users to read and accept the terms before using the wallet)

- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/3
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/4
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/5
