### ISSUE TITLE
Account Overview Dashboard

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#22]
Develop the account overview dashboard related features
(This group of screens will allow the user to `Change node settings` `Activate Account`)

**Stories:**
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/23
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/24
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/26
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/27
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/29
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/25
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/30
