### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#31]
Develop the account overview home dashboard
(This will allow the user to `Watch assets` `Watch Transactions History` `Get SIGNA value in other FIAT/Crypto currency`)

**Stories:**
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/32
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/33

**Related Epics:**
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/34
