### ISSUE TITLE
Market Rates Service

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#34]
- [x] Setup service for fetching multiple `FIAT/Crypto` rates
- [x] Persist the rates
- [x] Show it on the UI
- [x] Allow the user to pick between different rates to show on the wallet

**Currencies to be supported**
- USD
- EUR
- BTC
- BRL
- CAD
- GBP
- IDR
- RUB
- THB

We are going to use Coingecko's cryptocurrency data API
https://www.coingecko.com/en/api

_Thanks Coingecko for this awesome tool :D_
