### ISSUE TITLE
Token Screen

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#35]
Develop the account tokens screen
(This will allow the user to `Watch token holdings`)

**Stories:**
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/36
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/37
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/38
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/39

**Related Epics:**
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/34

![image](https://github.com/signum-network/signum-mobile-wallet/assets/35440957/68e4f05f-8b66-4d68-be4b-af9e4ff236ec)
