### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#40]
Develop the settings screen
(This will allow the user to customize their experience within the mobile wallet)

**Stories:**
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/41
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/42
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/43

**Related epic:**
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/22
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/44

![image](https://github.com/signum-network/signum-mobile-wallet/assets/35440957/0b906cf5-6387-4390-907d-e2cf9bdaa5d5)
