### ISSUE TITLE
Current Account Manager

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#44]
Develop account-management related features for handling multiple accounts

**Stories:**
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/45
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/46
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/47
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/48
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/49

![image](https://github.com/signum-network/signum-mobile-wallet/assets/35440957/03937fbb-2bb1-4da2-ad65-80b204e6a7c0)
![image](https://github.com/signum-network/signum-mobile-wallet/assets/35440957/04880724-6937-42a6-aa77-bbd38a492de6)
