### ISSUE TITLE
Transfer Funds Wizard

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#51]
Allow the user to easily send SIGNA or any Smart Token

**Stories:**
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/52
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/53
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/54
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/55
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/56
- [ ] https://github.com/signum-network/signum-mobile-wallet/issues/57

![image](https://github.com/signum-network/signum-mobile-wallet/assets/35440957/0b625b06-aa60-402b-94a8-adc384202dcd)
