### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-mobile-wallet#6]
Develop the account management related features
(This group of screens will allow the user to `Create` `Import` signum accounts)

**To discuss**
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/13

**Stories:**
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/7
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/8
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/9
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/14
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/15
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/10
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/11
- [x] https://github.com/signum-network/signum-mobile-wallet/issues/12

**Comment by ipr0310** [comment]
Final PR regarding initial account management is merged
https://github.com/signum-network/signum-mobile-wallet/pull/21
